"""Alter table movies

Revision ID: 3faacf2e27d3
Revises: a0cf26aa22a5
Create Date: 2025-11-09 17:30:56.541817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3faacf2e27d3'
down_revision: Union[str, Sequence[str], None] = 'a0cf26aa22a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('watched_movies', 'user_rating')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watched_movies', sa.Column('user_rating', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
