"""change table names

Revision ID: 60b934ac134f
Revises: c7bc9d29aa80
Create Date: 2026-01-14 05:37:42.978743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '60b934ac134f'
down_revision: Union[str, Sequence[str], None] = 'c7bc9d29aa80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('movies', 'content')
    op.rename_table('watched_movies', 'watched_content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('content', 'movies')
    op.rename_table('watched_content', 'watched_movies')
    # ### end Alembic commands ###
