"""Alter table movies

Revision ID: 66f5a30190f1
Revises: fb33425a8684
Create Date: 2025-11-09 17:21:25.321155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66f5a30190f1'
down_revision: Union[str, Sequence[str], None] = 'fb33425a8684'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'director')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('director', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
