"""add type to content table

Revision ID: 74c8b26bb3fe
Revises: 60b934ac134f
Create Date: 2026-01-14 06:09:28.989697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '74c8b26bb3fe'
down_revision: Union[str, Sequence[str], None] = '60b934ac134f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_series_tmdb_id'), table_name='series')
    op.drop_table('series')
    op.add_column('content', sa.Column('media_type', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_movies_tmdb_id'), table_name='content')
    op.create_index(op.f('ix_content_tmdb_id'), 'content', ['tmdb_id'], unique=True)
    op.add_column('watched_content', sa.Column('content_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_watched_movies_user_id'), table_name='watched_content')
    op.create_index(op.f('ix_watched_content_user_id'), 'watched_content', ['user_id'], unique=False)
    op.drop_constraint(op.f('watched_movies_movie_id_fkey'), 'watched_content', type_='foreignkey')
    op.create_foreign_key('watched_content_content_id_fkey', 'watched_content', 'content', ['content_id'], ['id'])
    op.drop_column('watched_content', 'movie_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watched_content', sa.Column('movie_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint('watched_content_content_id_fkey', 'watched_content', type_='foreignkey')
    op.create_foreign_key(op.f('watched_movies_movie_id_fkey'), 'watched_content', 'content', ['movie_id'], ['id'])
    op.drop_index(op.f('ix_watched_content_user_id'), table_name='watched_content')
    op.create_index(op.f('ix_watched_movies_user_id'), 'watched_content', ['user_id'], unique=False)
    op.drop_column('watched_content', 'content_id')
    op.drop_index(op.f('ix_content_tmdb_id'), table_name='content')
    op.create_index(op.f('ix_movies_tmdb_id'), 'content', ['tmdb_id'], unique=True)
    op.drop_column('content', 'media_type')
    op.create_table('series',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tmdb_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('genres', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('poster', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('series_pkey'))
    )
    op.create_index(op.f('ix_series_tmdb_id'), 'series', ['tmdb_id'], unique=True)
    # ### end Alembic commands ###
