"""Alter table movies

Revision ID: a0cf26aa22a5
Revises: 66f5a30190f1
Create Date: 2025-11-09 17:28:57.186754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0cf26aa22a5'
down_revision: Union[str, Sequence[str], None] = '66f5a30190f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('rating', sa.String(), nullable=False))
    op.drop_column('movies', 'imdb_rating')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('imdb_rating', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('movies', 'rating')
    # ### end Alembic commands ###
