"""drop rating & duration from movies

Revision ID: c7bc9d29aa80
Revises: f01c4b462923
Create Date: 2026-01-14 04:04:29.339254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7bc9d29aa80'
down_revision: Union[str, Sequence[str], None] = 'f01c4b462923'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'rating')
    op.drop_column('movies', 'duration')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('movies', sa.Column('rating', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
