"""Alter table movies

Revision ID: dc24b9191dba
Revises: 3faacf2e27d3
Create Date: 2025-11-09 18:31:17.009214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dc24b9191dba'
down_revision: Union[str, Sequence[str], None] = '3faacf2e27d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'rating',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('movies', 'genres',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_movies_tmdb_id'), table_name='movies')
    op.create_index(op.f('ix_movies_tmdb_id'), 'movies', ['tmdb_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movies_tmdb_id'), table_name='movies')
    op.create_index(op.f('ix_movies_tmdb_id'), 'movies', ['tmdb_id'], unique=False)
    op.alter_column('movies', 'genres',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('movies', 'rating',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
